create table public.base_link (
  id bigint generated by default as identity not null,
  name character varying null,
  type character varying null default 'trophy'::character varying,
  th numeric null default '18'::numeric,
  link character varying null,
  created_at timestamp with time zone not null default now(),
  constraint base_link_pkey primary key (id)
) TABLESPACE pg_default;