-- Profiles Table (extends auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  role text default 'member' check (role in ('admin', 'co_leader', 'elder', 'member')),
  avatar_url text,
  player_tag text,
  user_type text default 'viewer' check (user_type in ('admin', 'viewer')),
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Wars Table
create table public.wars (
  id uuid default uuid_generate_v4() primary key,
  opponent_name text not null,
  opponent_tag text,
  war_date timestamp with time zone not null,
  status text default 'preparation' check (status in ('preparation', 'active', 'ended')),
  result text check (result in ('victory', 'defeat', 'draw')),
  stars_us integer default 0,
  stars_them integer default 0,
  percentage_us numeric(5,2) default 0,
  percentage_them numeric(5,2) default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- War Performances Table (Who attacked whom)
create table public.war_performances (
  id uuid default uuid_generate_v4() primary key,
  war_id uuid references public.wars not null,
  profile_id uuid references public.profiles, -- can be null if member left but we keep stats?
  member_name text not null, -- snapshot of name
  stars integer default 0 check (stars >= 0 and stars <= 3),
  destruction numeric(5,2) default 0,
  town_hall_level integer,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Base Link Table (Actual Schema)
create table public.base_link (
  id bigint generated by default as identity not null,
  name character varying null,
  type character varying null default 'trophy'::character varying,
  th numeric null default '18'::numeric,
  link character varying null,
  created_at timestamp with time zone not null default now(),
  constraint base_link_pkey primary key (id)
);

-- Enable RLS
alter table public.base_link enable row level security;

-- Policies
create policy "Bases are viewable by everyone"
  on base_link for select
  using ( true );

create policy "Admins can insert bases"
  on base_link for insert
  with check ( 
    exists (
      select 1 from profiles
      where id = auth.uid()
      and user_type = 'admin'
    )
  );

-- Attack Strategies Table
create table public.strategies (
  id uuid default uuid_generate_v4() primary key,
  title text not null,
  description text,
  army_link text,
  video_url text,
  min_town_hall integer,
  type text check (type in ('ground', 'air', 'hybrid')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
