create table public.war_participants (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  war_id bigint not null,
  player_tag text not null,
  player_name text null,
  stars integer null default 0,
  destruction double precision null default 0,
  attacks_count integer null default 0,
  town_hall_level integer null,
  map_position integer null,
  constraint war_participants_pkey primary key (id),
  constraint war_participants_war_id_player_tag_key unique (war_id, player_tag),
  constraint war_participants_war_id_fkey foreign KEY (war_id) references war_history (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_war_participants_player_tag on public.war_participants using btree (player_tag) TABLESPACE pg_default;