create table public.war_history (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  start_date timestamp with time zone null,
  end_date timestamp with time zone not null,
  team_size integer null,
  clan_tag text not null,
  clan_name text null,
  clan_stars integer null,
  clan_destruction double precision null,
  opponent_tag text not null,
  opponent_name text null,
  opponent_stars integer null,
  opponent_destruction double precision null,
  result text null,
  constraint war_history_pkey primary key (id),
  constraint war_history_clan_tag_end_date_key unique (clan_tag, end_date),
  constraint fk_war_history_tracked_clan foreign KEY (clan_tag) references tracked_clans (tag) on delete CASCADE
) TABLESPACE pg_default;